name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them"
inputs:
  caching:
    description: "Whether to cache dep or not."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == "true"
      id: cache
      uses: actions/cache@v3
      with:
        path: second-action-react/node_modules
        key: deps-react-${{ hashFiles('second-action-react/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != "true"
      run: cd second-action-react && npm ci
      shell: bash
