name: Matrix Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/*"
      - "env-variables/*"
jobs:
  build:
    # continue-on-error: true if you want to continue with all jobs in matrix if one of the matrix fails
    strategy:
      matrix:
        node-version: [16, 18]
        operating-system: [ubuntu-latest]
        # include:
        #   - node-version: 18
        #     operating-system: windows
        # exclude:
        #   - node-version: 16
        #     operating-system: windows
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: second-action-react/node_modules
          key: deps-react-matrix-${{ hashFiles('second-action-react/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: cd second-action-react && npm ci
      - name: Build Project
        run: cd second-action-react && npm run build
