name: Second Workflow - Test Project & Deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd second-action-react
          npm ci
      - name: Run Tests
        run: cd second-action-react && npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd second-action-react
          npm ci
      - name: Build Project
        run: cd second-action-react && npm run build
      - name: Deploy
        run: echo "Deploying ..."