name: Second Workflow - Test Project & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - "dev-*" # dev-new dev-is-new
      - "feature/**" # feature/new feature/new/button
    branches-ignore: # ignore branches in this workflow
      - test
    paths-ignore: # ignore pathes for push
      - ".github/workflows/*"
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd second-action-react
          npm ci
      - name: Run Tests
        run: cd second-action-react && npm test
  deploy:
    # add waiting for testing jobs first, id needs missing it will run in parallel
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Code
        uses: actions/checkout@v3
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: |
          cd second-action-react
          npm ci
      - name: Build Project
        run: cd second-action-react && npm run build
      - name: Deploy
        run: echo "Deploying ..."
