name: Use Reusable
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"
  deploy:
    uses: ./.github/workflows/reusable-actions.yaml
