name: Use Reusable
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done - bye!"
  deploy:
    uses: ./.github/workflows/reusable-actions.yaml
    # with:
    #   artifact-name: dist-files
    # secrets:
    #   some-secret: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
  # print-deploy-result:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Print Deploy output
  #       run: echo "${{needs.deploy.outputs.result}}."
